-- Mark orchestrator-dispatched remediation tasks so the scheduler can treat
-- them differently from feature work:
--   * they jump to the FRONT of the author's queue (a changes-requested PR
--     blocks an in_review slot, so its fix outranks new features), and
--   * they are EXEMPT from the WORKER_MAX_IN_REVIEW capacity guard — a fix
--     task exists precisely to drain in_review debt. Counting it against the
--     cap deadlocks the worker: in_review tasks wait for the fix, the fix
--     waits for a free slot.
--
-- kind: NULL for regular tasks; 'review_fix' for author fix tasks dispatched
--       by the orchestrator on a changes-requested review.
ALTER TABLE worker_tasks ADD COLUMN kind TEXT;

-- Backfill fix tasks already sitting in queues (dispatched before this
-- migration), so live deployments self-heal from the deadlock on restart.
-- The title is machine-generated by dispatch_author_fix_task, so the LIKE
-- match is exact by construction.
UPDATE worker_tasks
   SET kind = 'review_fix'
 WHERE status = 'queued'
   AND title LIKE 'Atendé el review del PR #%';
