-- 20260803000000 backfilled kind='review_fix' only for QUEUED fix tasks (the
-- deadlock being fixed). Fix tasks that were already past queued (in_review /
-- in_progress / done) kept kind = NULL, which makes them invisible to the
-- merged-PR reconciliation sweep — they stay in_review forever after their PR
-- merges (the "MERGED badge but card never closes" bug).
--
-- The title is machine-generated by dispatch_author_fix_task, so the LIKE
-- prefix match is exact by construction (it also matches the newer
-- "— ronda N" suffixed titles).
UPDATE worker_tasks
   SET kind = 'review_fix'
 WHERE kind IS NULL
   AND title LIKE 'Atendé el review del PR #%';
