import { useEffect, useState, type ReactNode } from 'react';
import { useQuery } from '@tanstack/react-query';
import { create, useModal } from '@ebay/nice-modal-react';
import { useTranslation } from 'react-i18next';
import {
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  HelpCircle,
  Loader2,
} from 'lucide-react';
import { Button } from '@vibe/ui/components/Button';
import { Input } from '@vibe/ui/components/Input';
import { Textarea } from '@vibe/ui/components/Textarea';
import { Label } from '@vibe/ui/components/Label';
import { Alert, AlertDescription, AlertTitle } from '@vibe/ui/components/Alert';
import { Tooltip } from '@vibe/ui/components/Tooltip';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@vibe/ui/components/KeyboardDialog';
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from '@vibe/ui/components/Select';
import {
  BaseCodingAgent,
  type ModelSelectorConfig,
  type WorkerResponse,
} from 'shared/types';
import { defineModal } from '@/shared/lib/modals';
import { SettingsDialog } from '@/shared/dialogs/settings/SettingsDialog';
import {
  agentAuthApi,
  workersApi,
  type AgentAuthProvider,
  type CreateWorkerRequest,
} from '@/shared/lib/api';
import {
  useBaseInstructions,
  useCreateWorker,
  useUpdateWorker,
} from '@/features/workers/model/useWorkers';
import {
  SOUL_TEMPLATES,
  type SoulTemplateId,
} from '@/features/workers/model/soulTemplates';
import { useUserSystem } from '@/shared/hooks/useUserSystem';
import { useModelSelectorConfig } from '@/shared/hooks/useExecutorDiscovery';
import { cn } from '@/shared/lib/utils';

export const WORKER_ROLES = [
  'developer',
  'analyst',
  'reviewer',
  'designer',
  'qa',
  'devops',
  'architect',
  'docs',
  'quality',
  'security',
] as const;
export type WorkerRole = (typeof WORKER_ROLES)[number];

// Where a profile joins the flow of an issue. Mirror of
// `worker::can_join_stage`: phases before development and gates run as
// specialists (no PR of their own); the implementer opens the PR.
const FLOW_STAGES = ['pre_dev', 'implement', 'gate'] as const;
type FlowStage = (typeof FLOW_STAGES)[number];
const SPECIALIST_ROLES: readonly string[] = [
  'qa',
  'architect',
  'docs',
  'quality',
  'security',
];
const canJoinStage = (role: string, stage: FlowStage): boolean =>
  stage === 'implement'
    ? role === 'developer' || role === 'devops'
    : SPECIALIST_ROLES.includes(role);

// Temporary augmentation: the backend now returns `has_github_pat: boolean`,
// `plan_mode: boolean | null` and `gh_write_warning: boolean`, but
// `shared/types.ts` is regenerated by ts-rs and must not be hand-edited.
// Until infra regenerates it, read the fields through this optional
// intersection so tsc stays happy without touching the generated file.
type WorkerResponseWithOverrides = WorkerResponse & {
  has_github_pat?: boolean;
  plan_mode?: boolean | null;
  gh_write_warning?: boolean;
};
const hasStoredPat = (worker: WorkerResponse | undefined): boolean =>
  (worker as WorkerResponseWithOverrides | undefined)?.has_github_pat === true;
const readPlanMode = (worker: WorkerResponse | undefined): boolean | null =>
  (worker as WorkerResponseWithOverrides | undefined)?.plan_mode ?? null;
const readGhWriteWarning = (worker: WorkerResponse | undefined): boolean =>
  (worker as WorkerResponseWithOverrides | undefined)?.gh_write_warning ===
  true;

// Mirror of `utils::text::has_gh_write_patterns` (issue #550). Kept in
// lockstep with the CI factory-guard for repo prompts (issue #549) so the
// live UX and the server share one definition of "gh write".
const GH_WRITE_PATTERN =
  /gh\s+(pr|issue)\s+(create|close|comment|review)\b|gh\s+api\s+-X\s+(POST|PATCH|DELETE)\b/;
const soulHasGhWritePatterns = (soul: string): boolean =>
  GH_WRITE_PATTERN.test(soul);

// The API still requires an emoji; the UI no longer exposes it.
const DEFAULT_WORKER_EMOJI = '🤖';

// Sentinel value used in the Select to represent "no override" (null agent
// and model: follow the global default).
const MODEL_DEFAULT_VALUE = '__default__';

// Providers a worker can pick a model from, in display order, with the slug
// the agent-auth endpoint reports their connection under.
const MODEL_PROVIDERS: {
  agent: BaseCodingAgent;
  auth: AgentAuthProvider;
  name: string;
}[] = [
  { agent: BaseCodingAgent.CLAUDE_CODE, auth: 'claude_code', name: 'Claude' },
  { agent: BaseCodingAgent.CODEX, auth: 'codex', name: 'Codex' },
  { agent: BaseCodingAgent.GEMINI, auth: 'gemini', name: 'Gemini' },
];
// Claude CLI aliases (mirror of `claude/models.rs::fallback_models`). The
// CLI accepts them even when the catalog comes from the Anthropic API and
// lists only full ids, so they never count as "not available".
const CLAUDE_CLI_ALIASES = ['opus', 'opus[1m]', 'sonnet', 'haiku', 'fable'];
const providerName = (agent: BaseCodingAgent): string =>
  MODEL_PROVIDERS.find((p) => p.agent === agent)?.name ?? agent;

// Select values for a concrete pick are `AGENT::model`.
const toModelValue = (agent: BaseCodingAgent, model: string) =>
  `${agent}::${model}`;
const fromModelValue = (
  value: string
): { executor: BaseCodingAgent; model: string } => {
  const [executor, ...rest] = value.split('::');
  return { executor: executor as BaseCodingAgent, model: rest.join('::') };
};

// Sentinel values for the three-state plan mode selector. `global` maps to
// `null` on the wire (follow global setting); `on` / `off` explicitly force
// plan mode for the worker regardless of the global.
const PLAN_MODE_GLOBAL = '__global__';
const PLAN_MODE_ON = 'on';
const PLAN_MODE_OFF = 'off';
type PlanModeChoice =
  | typeof PLAN_MODE_GLOBAL
  | typeof PLAN_MODE_ON
  | typeof PLAN_MODE_OFF;

const planModeToChoice = (value: boolean | null): PlanModeChoice => {
  if (value === true) return PLAN_MODE_ON;
  if (value === false) return PLAN_MODE_OFF;
  return PLAN_MODE_GLOBAL;
};

const choiceToPlanMode = (choice: PlanModeChoice): boolean | null => {
  if (choice === PLAN_MODE_ON) return true;
  if (choice === PLAN_MODE_OFF) return false;
  return null;
};

function LabelWithHelp({
  htmlFor,
  label,
  help,
}: {
  htmlFor: string;
  label: string;
  help: string;
}) {
  return (
    <div className="flex items-center gap-1.5">
      <Label htmlFor={htmlFor}>{label}</Label>
      <Tooltip content={help} side="right">
        <button
          type="button"
          aria-label={help}
          className="inline-flex items-center justify-center rounded text-low hover:text-normal focus:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        >
          <HelpCircle className="h-3.5 w-3.5" aria-hidden />
        </button>
      </Tooltip>
    </div>
  );
}

function SectionHeader({ children }: { children: ReactNode }) {
  return (
    <div className="mt-2 border-b border-border pb-1 text-label font-semibold uppercase tracking-wider text-low">
      {children}
    </div>
  );
}

export interface WorkerFormDialogProps {
  worker?: WorkerResponse;
}

export type WorkerFormResult = 'saved' | 'canceled';

const WorkerFormDialogImpl = create<WorkerFormDialogProps>(({ worker }) => {
  const modal = useModal();
  const { t } = useTranslation('common');
  const isEdit = !!worker;

  const [name, setName] = useState(worker?.name ?? '');
  const [soul, setSoul] = useState(worker?.soul ?? '');
  const [role, setRole] = useState<WorkerRole>(
    (worker?.role as WorkerRole) ?? 'developer'
  );
  const [executor, setExecutor] = useState<BaseCodingAgent | null>(
    worker?.executor ?? null
  );
  const [model, setModel] = useState<string | null>(worker?.model ?? null);
  const [planMode, setPlanMode] = useState<PlanModeChoice>(
    planModeToChoice(readPlanMode(worker))
  );
  const [flowStage, setFlowStage] = useState<FlowStage | null>(
    (worker?.flow?.stage as FlowStage | null) ?? null
  );
  const [flowAlways, setFlowAlways] = useState(worker?.flow?.always ?? false);
  const [flowOfferWhen, setFlowOfferWhen] = useState(
    worker?.flow?.offer_when ?? ''
  );
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // PAT field state.
  //   - `githubPat === null`  → do not touch the stored value (edit mode
  //                             with an existing PAT that the user hasn't
  //                             replaced, OR create mode with no token).
  //   - `githubPat === ''`    → clear the stored value on save.
  //   - `githubPat === <str>` → new value to persist (validated first).
  // We keep the input value separately from what we send to the API so the
  // masked placeholder can render without leaking the real token.
  const [githubPat, setGithubPat] = useState<string | null>(null);
  const [clearPat, setClearPat] = useState(false);
  const [patValidation, setPatValidation] = useState<
    | { status: 'idle' }
    | { status: 'validating' }
    | { status: 'ok'; login: string }
    | { status: 'error'; message: string }
  >({ status: 'idle' });

  const [baseInstructionsExpanded, setBaseInstructionsExpanded] =
    useState(false);
  const { data: baseInstructions } = useBaseInstructions();

  const { config: systemConfig } = useUserSystem();
  const configuredExecutor = systemConfig?.executor_profile?.executor ?? null;

  // A provider is usable when it is connected, or when it is the global
  // default. Same rule as the orchestrator's start gate, which never gates
  // the global agent and reads the same connection check as this endpoint.
  const { data: authStatus, isSuccess: authLoaded } = useQuery({
    queryKey: ['agent-auth-status'],
    queryFn: () => agentAuthApi.getStatus(),
  });
  const isConnected = (agent: BaseCodingAgent): boolean => {
    const auth = MODEL_PROVIDERS.find((p) => p.agent === agent)?.auth;
    return (
      agent === configuredExecutor ||
      !!authStatus?.providers.some((p) => p.provider === auth && p.connected)
    );
  };
  // Only claim "not connected" once the status loaded, so the dialog does
  // not flash disconnected groups and alerts while the query is in flight.
  const isDisconnected = (agent: BaseCodingAgent): boolean =>
    authLoaded && !isConnected(agent);
  const claudeConfig = useModelSelectorConfig(
    isConnected(BaseCodingAgent.CLAUDE_CODE)
      ? BaseCodingAgent.CLAUDE_CODE
      : null
  ).config;
  const codexConfig = useModelSelectorConfig(
    isConnected(BaseCodingAgent.CODEX) ? BaseCodingAgent.CODEX : null
  ).config;
  const geminiConfig = useModelSelectorConfig(
    isConnected(BaseCodingAgent.GEMINI) ? BaseCodingAgent.GEMINI : null
  ).config;
  const configByAgent: Partial<
    Record<BaseCodingAgent, ModelSelectorConfig | null>
  > = {
    [BaseCodingAgent.CLAUDE_CODE]: claudeConfig,
    [BaseCodingAgent.CODEX]: codexConfig,
    [BaseCodingAgent.GEMINI]: geminiConfig,
  };
  // Display name of the model the agent runs when none is pinned.
  const baseModelName = (agent: BaseCodingAgent): string | null => {
    const cfg = configByAgent[agent];
    if (!cfg?.default_model) return null;
    return (
      cfg.models.find((m) => m.id === cfg.default_model)?.name ??
      cfg.default_model
    );
  };
  const openAgentConnections = () =>
    void SettingsDialog.show({ initialSection: 'agents' });

  const createMutation = useCreateWorker();
  const updateMutation = useUpdateWorker();
  const isSubmitting = createMutation.isPending || updateMutation.isPending;

  useEffect(() => {
    setName(worker?.name ?? '');
    setSoul(worker?.soul ?? '');
    setRole((worker?.role as WorkerRole) ?? 'developer');
    setExecutor(worker?.executor ?? null);
    setModel(worker?.model ?? null);
    setPlanMode(planModeToChoice(readPlanMode(worker)));
    setFlowStage((worker?.flow?.stage as FlowStage | null) ?? null);
    setFlowAlways(worker?.flow?.always ?? false);
    setFlowOfferWhen(worker?.flow?.offer_when ?? '');
    setGithubPat(null);
    setClearPat(false);
    setPatValidation({ status: 'idle' });
    setErrorMessage(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [worker?.id]);

  useEffect(() => {
    setErrorMessage(null);
  }, [
    name,
    soul,
    role,
    executor,
    model,
    planMode,
    githubPat,
    clearPat,
    flowStage,
  ]);

  // A role that cannot join the chosen stage takes the profile out of it.
  const changeRole = (next: WorkerRole) => {
    setRole(next);
    if (flowStage && !canJoinStage(next, flowStage)) setFlowStage(null);
  };

  const applyTemplate = (templateId: SoulTemplateId) => {
    const template = SOUL_TEMPLATES.find((tpl) => tpl.id === templateId);
    if (!template) return;
    setSoul(template.soul);
    if (template.role) changeRole(template.role);
  };

  const handleCancel = () => {
    modal.resolve('canceled' as WorkerFormResult);
    modal.hide();
  };

  const handleOpenChange = (open: boolean) => {
    if (!open) handleCancel();
  };

  const handleValidatePat = async () => {
    const trimmed = (githubPat ?? '').trim();
    if (!trimmed) return;
    setPatValidation({ status: 'validating' });
    try {
      const { login } = await workersApi.validateGithubPat(trimmed);
      setPatValidation({ status: 'ok', login });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      setPatValidation({ status: 'error', message });
    }
  };

  const handleSubmit = async () => {
    const trimmedName = name.trim();
    const trimmedSoul = soul.trim();
    if (!trimmedName || !trimmedSoul) return;

    // Decide what to send for github_pat:
    //   - `undefined` → don't touch (server keeps the stored value)
    //   - `null`      → clear the stored token
    //   - `string`    → replace with this value
    // On create there is nothing to clear, so we drop `null` outright and
    // only send a string when the user typed something.
    let github_pat: string | null | undefined;
    const trimmedPat = (githubPat ?? '').trim();
    if (isEdit) {
      if (clearPat) {
        github_pat = null;
      } else if (trimmedPat.length > 0) {
        github_pat = trimmedPat;
      } else {
        github_pat = undefined;
      }
    } else if (trimmedPat.length > 0) {
      github_pat = trimmedPat;
    } else {
      github_pat = undefined;
    }

    const payload: CreateWorkerRequest = {
      name: trimmedName,
      emoji: worker?.emoji ?? DEFAULT_WORKER_EMOJI,
      soul: trimmedSoul,
      role,
      executor,
      model: model ?? null,
      plan_mode: choiceToPlanMode(planMode),
      ...(github_pat === undefined ? {} : { github_pat }),
      ...(isEdit || flowStage
        ? {
            flow: {
              stage: flowStage,
              // The implementer is chosen per issue; "always" means nothing there.
              always: flowStage !== 'implement' && flowAlways,
              offer_when: flowOfferWhen.trim() || null,
            },
          }
        : {}),
    };

    try {
      if (isEdit && worker) {
        await updateMutation.mutateAsync({
          workerId: worker.id,
          data: payload,
        });
      } else {
        await createMutation.mutateAsync(payload);
      }
      modal.resolve('saved' as WorkerFormResult);
      modal.hide();
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      setErrorMessage(message);
    }
  };

  const canSubmit =
    name.trim().length > 0 && soul.trim().length > 0 && !isSubmitting;

  // Warning drives from live textarea contents so the user sees it flip as
  // they edit; falls back to the server's authoritative flag from the loaded
  // response for the initial paint before any keystroke. Non-blocking:
  // saving stays allowed to support gradual migration.
  const soulUnchanged = (worker?.soul ?? '') === soul;
  const showGhWriteWarning = soulUnchanged
    ? readGhWriteWarning(worker) || soulHasGhWritePatterns(soul)
    : soulHasGhWritePatterns(soul);

  // The saved pick is flagged when its provider is disconnected (the task
  // will fail to start) or its model left the provider's list (the task
  // falls back to the provider's default model).
  const pickedAgent = executor ?? (model ? configuredExecutor : null);
  const pickedDisconnected = !!pickedAgent && isDisconnected(pickedAgent);
  const pickedModels = pickedAgent
    ? configByAgent[pickedAgent]?.models
    : undefined;
  const pickedUnavailable =
    !!pickedAgent &&
    !!model &&
    !pickedDisconnected &&
    !!pickedModels?.length &&
    !pickedModels.some((m) => m.id === model) &&
    !(
      pickedAgent === BaseCodingAgent.CLAUDE_CODE &&
      CLAUDE_CLI_ALIASES.includes(model)
    );
  const connectedProviders = MODEL_PROVIDERS.filter((p) =>
    isConnected(p.agent)
  );
  const disconnectedProviders = MODEL_PROVIDERS.filter((p) =>
    isDisconnected(p.agent)
  );
  // "Por defecto" reads as "Provider · base model", like the mock (#612).
  const defaultBase = configuredExecutor
    ? [providerName(configuredExecutor), baseModelName(configuredExecutor)]
        .filter(Boolean)
        .join(' · ')
    : null;
  const defaultLabel = defaultBase
    ? `${t('workers.form.modelDefault')} · ${defaultBase}`
    : t('workers.form.modelDefault');

  const selectValue =
    pickedAgent && model
      ? toModelValue(pickedAgent, model)
      : pickedAgent
        ? toModelValue(pickedAgent, '')
        : MODEL_DEFAULT_VALUE;
  const pickedLabel = pickedAgent
    ? `${model ?? t('workers.form.modelProviderDefault')} · ${providerName(pickedAgent)}`
    : null;

  return (
    <Dialog open={modal.visible} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-[640px]">
        <DialogHeader>
          <DialogTitle>
            {isEdit ? t('workers.form.editTitle') : t('workers.form.newTitle')}
          </DialogTitle>
          <DialogDescription>{t('workers.form.description')}</DialogDescription>
        </DialogHeader>

        <div className="space-y-3 py-2">
          <SectionHeader>{t('workers.form.sectionConfig')}</SectionHeader>

          <div>
            <Label htmlFor="worker-name">{t('workers.form.nameLabel')}</Label>
            <Input
              id="worker-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder={t('workers.form.namePlaceholder')}
              autoFocus
              className="mt-1"
            />
          </div>

          {/* Fluke (the Director) keeps its role: it is the only orchestrator. */}
          {worker?.role !== 'orchestrator' && (
            <div>
              <LabelWithHelp
                htmlFor="worker-role"
                label={t('workers.form.roleLabel')}
                help={t(`workers.roles.${role}Description`)}
              />
              <Select
                value={role}
                onValueChange={(v) => changeRole(v as WorkerRole)}
              >
                <SelectTrigger id="worker-role" className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {WORKER_ROLES.map((r) => (
                    <SelectItem key={r} value={r}>
                      {t(`workers.roles.${r}`)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          <div>
            <Label htmlFor="worker-model">{t('workers.form.modelLabel')}</Label>
            <Select
              value={selectValue}
              onValueChange={(v) => {
                if (v === MODEL_DEFAULT_VALUE) {
                  setExecutor(null);
                  setModel(null);
                  return;
                }
                const picked = fromModelValue(v);
                setExecutor(picked.executor);
                setModel(picked.model || null);
              }}
            >
              <SelectTrigger id="worker-model" className="mt-1">
                <SelectValue>
                  {pickedLabel ?? defaultLabel}
                  {pickedDisconnected &&
                    ` · ${t('workers.form.modelProviderDisconnected')}`}
                  {pickedUnavailable &&
                    ` · ${t('workers.form.modelUnavailable')}`}
                </SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={MODEL_DEFAULT_VALUE}>
                  {defaultLabel}
                </SelectItem>
                {(pickedDisconnected || pickedUnavailable) && (
                  <SelectItem value={selectValue} disabled>
                    {pickedLabel} ·{' '}
                    {pickedDisconnected
                      ? t('workers.form.modelProviderDisconnected')
                      : t('workers.form.modelUnavailable')}
                  </SelectItem>
                )}
                {connectedProviders.map((p) => (
                  <SelectGroup key={p.agent}>
                    <SelectSeparator />
                    <SelectLabel>
                      {p.name}
                      {p.agent === configuredExecutor &&
                        ` · ${t('workers.form.modelProviderIsDefault')}`}
                    </SelectLabel>
                    <SelectItem value={toModelValue(p.agent, '')}>
                      {t('workers.form.modelProviderDefault')}
                      {baseModelName(p.agent) && ` (${baseModelName(p.agent)})`}
                    </SelectItem>
                    {(configByAgent[p.agent]?.models ?? []).map((m) => (
                      <SelectItem
                        key={m.id}
                        value={toModelValue(p.agent, m.id)}
                      >
                        {m.name}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                ))}
                {disconnectedProviders.length > 0 && (
                  <SelectGroup>
                    <SelectSeparator />
                    <SelectLabel>
                      {t('workers.form.modelNotConnectedGroup')}
                    </SelectLabel>
                    {disconnectedProviders.map((p) => (
                      <SelectItem
                        key={p.agent}
                        value={`__off__${p.agent}`}
                        disabled
                      >
                        {p.name} · {t('workers.form.modelNotConnected')}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                )}
              </SelectContent>
            </Select>
            {pickedDisconnected && pickedAgent && (
              <p className="mt-1 text-xs text-destructive" role="alert">
                {t('workers.form.modelProviderDisconnectedHelp', {
                  provider: providerName(pickedAgent),
                })}{' '}
                <button
                  type="button"
                  onClick={openAgentConnections}
                  className="underline"
                >
                  {t('workers.form.modelConnectProvider', {
                    provider: providerName(pickedAgent),
                  })}
                </button>
              </p>
            )}
            {pickedUnavailable && pickedAgent && (
              <p className="mt-1 text-xs text-warning" role="status">
                {t('workers.form.modelUnavailableHelp', {
                  model,
                  provider: providerName(pickedAgent),
                })}
              </p>
            )}
            <p className="mt-1 text-xs text-low">
              {t('workers.form.modelHelp')}
              {disconnectedProviders.length > 0 && (
                <>
                  {' '}
                  <button
                    type="button"
                    onClick={openAgentConnections}
                    className="underline hover:text-normal"
                  >
                    {t('workers.form.modelConnectProviders')}
                  </button>
                </>
              )}
            </p>
          </div>

          <div>
            <LabelWithHelp
              htmlFor="worker-plan-mode"
              label={t('workers.form.planModeLabel')}
              help={t('workers.form.planModeHelp')}
            />
            <Select
              value={planMode}
              onValueChange={(v) => setPlanMode(v as PlanModeChoice)}
            >
              <SelectTrigger id="worker-plan-mode" className="mt-1">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={PLAN_MODE_GLOBAL}>
                  {t('workers.form.planModeGlobal')}
                </SelectItem>
                <SelectItem value={PLAN_MODE_ON}>
                  {t('workers.form.planModeOn')}
                </SelectItem>
                <SelectItem value={PLAN_MODE_OFF}>
                  {t('workers.form.planModeOff')}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          {worker?.role !== 'orchestrator' && (
            <>
              <SectionHeader>{t('workers.form.flow.section')}</SectionHeader>
              <div
                role="radiogroup"
                aria-label={t('workers.form.flow.section')}
                className="grid gap-1.5 sm:grid-cols-3"
              >
                {FLOW_STAGES.map((stage) => {
                  const allowed = canJoinStage(role, stage);
                  const on = flowStage === stage;
                  return (
                    <button
                      key={stage}
                      type="button"
                      role="radio"
                      aria-checked={on}
                      disabled={!allowed}
                      // Clicking the chosen stage again takes the profile out.
                      onClick={() => setFlowStage(on ? null : stage)}
                      className={cn(
                        'grid content-start gap-0.5 rounded-md border px-2.5 py-2 text-left',
                        on
                          ? 'border-brand ring-1 ring-brand'
                          : 'border-border hover:border-low',
                        !allowed && 'cursor-not-allowed opacity-50'
                      )}
                    >
                      <b className="text-sm font-semibold text-high">
                        {t(`workers.form.flow.stage.${stage}`)}
                      </b>
                      <span className="text-xs leading-snug text-low">
                        {allowed
                          ? t(`workers.form.flow.stageHelp.${stage}`)
                          : t('workers.form.flow.roleCannot', {
                              role: t(`workers.roles.${role}`),
                            })}
                      </span>
                    </button>
                  );
                })}
              </div>
              {!flowStage ? (
                <p className="text-xs text-low">
                  {t('workers.form.flow.none')}
                </p>
              ) : (
                <>
                  {flowStage !== 'implement' && (
                    <div
                      role="radiogroup"
                      aria-label={t('workers.form.flow.when')}
                      className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm"
                    >
                      <span className="text-xs font-medium text-normal">
                        {t('workers.form.flow.when')}
                      </span>
                      {[false, true].map((always) => (
                        <label
                          key={String(always)}
                          className="inline-flex items-center gap-1.5"
                        >
                          <input
                            type="radio"
                            name="worker-flow-when"
                            checked={flowAlways === always}
                            onChange={() => setFlowAlways(always)}
                          />
                          {always
                            ? t('workers.form.flow.always')
                            : t('workers.form.flow.onDemand')}
                        </label>
                      ))}
                    </div>
                  )}
                  {!(flowStage !== 'implement' && flowAlways) && (
                    <div>
                      <LabelWithHelp
                        htmlFor="worker-flow-offer"
                        label={t('workers.form.flow.offerWhen')}
                        help={t('workers.form.flow.offerWhenHelp')}
                      />
                      <Input
                        id="worker-flow-offer"
                        value={flowOfferWhen}
                        onChange={(e) => setFlowOfferWhen(e.target.value)}
                        placeholder={t(
                          'workers.form.flow.offerWhenPlaceholder'
                        )}
                        className="mt-1"
                      />
                    </div>
                  )}
                  <p className="text-xs text-low">
                    {t(`workers.form.flow.contract.${flowStage}`)}
                    {worker?.flow?.slug &&
                      ` ${t('workers.form.flow.slug', { slug: worker.flow.slug })}`}
                  </p>
                </>
              )}
            </>
          )}

          <SectionHeader>{t('workers.form.sectionIntegration')}</SectionHeader>

          <div>
            <Label htmlFor="worker-github-pat">
              {t('workers.form.githubPatLabel')}
            </Label>
            <div className="mt-1 flex gap-2">
              <Input
                id="worker-github-pat"
                type="password"
                autoComplete="new-password"
                value={githubPat ?? ''}
                onChange={(e) => {
                  setGithubPat(e.target.value);
                  setClearPat(false);
                  setPatValidation({ status: 'idle' });
                }}
                placeholder={
                  isEdit && hasStoredPat(worker) && !clearPat
                    ? t('workers.form.githubPatMaskedPlaceholder')
                    : t('workers.form.githubPatPlaceholder')
                }
                className="flex-1"
              />
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleValidatePat}
                disabled={
                  patValidation.status === 'validating' ||
                  !(githubPat ?? '').trim()
                }
              >
                {patValidation.status === 'validating' && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                {t('workers.form.githubPatValidate')}
              </Button>
            </div>
            {patValidation.status === 'ok' && (
              <p className="mt-1 flex items-center gap-1 text-xs text-green-600">
                <CheckCircle2 className="h-3 w-3" />
                {t('workers.form.githubPatValidateOk', {
                  login: patValidation.login,
                })}
              </p>
            )}
            {patValidation.status === 'error' && (
              <p className="mt-1 text-xs text-destructive">
                {patValidation.message}
              </p>
            )}
            <p className="mt-1 text-xs text-low">
              {t('workers.form.githubPatHelp')}
            </p>
            {isEdit && hasStoredPat(worker) && (
              <div className="mt-1 flex items-center gap-2 text-xs">
                <span className="text-low">
                  {clearPat
                    ? t('workers.form.githubPatWillClear')
                    : t('workers.form.githubPatStored')}
                </span>
                {!clearPat ? (
                  <button
                    type="button"
                    onClick={() => {
                      setClearPat(true);
                      setGithubPat('');
                      setPatValidation({ status: 'idle' });
                    }}
                    className="text-destructive underline"
                  >
                    {t('workers.form.githubPatClear')}
                  </button>
                ) : (
                  <button
                    type="button"
                    onClick={() => setClearPat(false)}
                    className="text-low underline"
                  >
                    {t('workers.form.githubPatUndoClear')}
                  </button>
                )}
              </div>
            )}
          </div>

          <SectionHeader>{t('workers.form.sectionSoul')}</SectionHeader>

          {!isEdit && (
            <div>
              <p className="text-xs text-low mb-1">
                {t('workers.form.templatesLabel')}
              </p>
              <div className="flex flex-wrap gap-2">
                {SOUL_TEMPLATES.map((tpl) => (
                  <Button
                    key={tpl.id}
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => applyTemplate(tpl.id)}
                  >
                    {t(tpl.labelKey)}
                  </Button>
                ))}
              </div>
            </div>
          )}

          <div className="rounded border">
            <button
              type="button"
              onClick={() => setBaseInstructionsExpanded((prev) => !prev)}
              className="flex w-full items-center gap-1.5 px-3 py-2 text-xs text-low hover:text-normal"
            >
              {baseInstructionsExpanded ? (
                <ChevronDown className="h-3 w-3 shrink-0" />
              ) : (
                <ChevronRight className="h-3 w-3 shrink-0" />
              )}
              <span className="font-medium">
                {t('workers.form.systemInstructionsTitle')}
              </span>
              <span className="ml-1 text-low">
                {t('workers.form.systemInstructionsReadOnly')}
              </span>
            </button>
            {baseInstructionsExpanded && (
              <pre className="max-h-48 overflow-auto border-t px-3 py-2 font-mono text-xs text-low whitespace-pre-wrap">
                {baseInstructions ?? '…'}
              </pre>
            )}
          </div>

          <div>
            <Label htmlFor="worker-soul">{t('workers.form.soulLabel')}</Label>
            <Textarea
              id="worker-soul"
              value={soul}
              onChange={(e) => setSoul(e.target.value)}
              rows={6}
              className="mt-1 font-mono text-sm resize-y min-h-[96px]"
              placeholder={t('workers.form.soulPlaceholder')}
            />
          </div>

          {showGhWriteWarning && (
            <Alert variant="warning">
              <AlertTitle>{t('workers.form.ghWriteWarningTitle')}</AlertTitle>
              <AlertDescription>
                {t('workers.form.ghWriteWarningBody')}
              </AlertDescription>
            </Alert>
          )}

          {errorMessage && <Alert variant="destructive">{errorMessage}</Alert>}
        </div>

        <DialogFooter className="border-t border-border/60 pt-4">
          <Button variant="outline" onClick={handleCancel}>
            {t('workers.form.cancel')}
          </Button>
          <Button onClick={handleSubmit} disabled={!canSubmit}>
            {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            {isEdit ? t('workers.form.saveEdit') : t('workers.form.saveNew')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
});

export const WorkerFormDialog = defineModal<
  WorkerFormDialogProps,
  WorkerFormResult
>(WorkerFormDialogImpl);
