import { useEffect, useState, type ReactNode } from 'react';
import { create, useModal } from '@ebay/nice-modal-react';
import { useTranslation } from 'react-i18next';
import {
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  HelpCircle,
  Loader2,
} from 'lucide-react';
import { Button } from '@vibe/ui/components/Button';
import { Input } from '@vibe/ui/components/Input';
import { Textarea } from '@vibe/ui/components/Textarea';
import { Label } from '@vibe/ui/components/Label';
import { Alert, AlertDescription, AlertTitle } from '@vibe/ui/components/Alert';
import { Tooltip } from '@vibe/ui/components/Tooltip';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@vibe/ui/components/KeyboardDialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@vibe/ui/components/Select';
import type { WorkerResponse } from 'shared/types';
import { defineModal } from '@/shared/lib/modals';
import { workersApi, type CreateWorkerRequest } from '@/shared/lib/api';
import {
  useBaseInstructions,
  useCreateWorker,
  useUpdateWorker,
} from '@/features/workers/model/useWorkers';
import {
  SOUL_TEMPLATES,
  type SoulTemplateId,
} from '@/features/workers/model/soulTemplates';
import { useUserSystem } from '@/shared/hooks/useUserSystem';
import { useModelSelectorConfig } from '@/shared/hooks/useExecutorDiscovery';

export const WORKER_ROLES = [
  'developer',
  'analyst',
  'reviewer',
  'designer',
] as const;
export type WorkerRole = (typeof WORKER_ROLES)[number];

// Temporary augmentation: the backend now returns `has_github_pat: boolean`,
// `plan_mode: boolean | null` and `gh_write_warning: boolean`, but
// `shared/types.ts` is regenerated by ts-rs and must not be hand-edited.
// Until infra regenerates it, read the fields through this optional
// intersection so tsc stays happy without touching the generated file.
type WorkerResponseWithOverrides = WorkerResponse & {
  has_github_pat?: boolean;
  plan_mode?: boolean | null;
  gh_write_warning?: boolean;
};
const hasStoredPat = (worker: WorkerResponse | undefined): boolean =>
  (worker as WorkerResponseWithOverrides | undefined)?.has_github_pat === true;
const readPlanMode = (worker: WorkerResponse | undefined): boolean | null =>
  (worker as WorkerResponseWithOverrides | undefined)?.plan_mode ?? null;
const readGhWriteWarning = (worker: WorkerResponse | undefined): boolean =>
  (worker as WorkerResponseWithOverrides | undefined)?.gh_write_warning ===
  true;

// Mirror of `utils::text::has_gh_write_patterns` (issue #550). Kept in
// lockstep with the CI factory-guard for repo prompts (issue #549) so the
// live UX and the server share one definition of "gh write".
const GH_WRITE_PATTERN =
  /gh\s+(pr|issue)\s+(create|close|comment|review)\b|gh\s+api\s+-X\s+(POST|PATCH|DELETE)\b/;
const soulHasGhWritePatterns = (soul: string): boolean =>
  GH_WRITE_PATTERN.test(soul);

// The API still requires an emoji; the UI no longer exposes it.
const DEFAULT_WORKER_EMOJI = '🤖';

// Sentinel value used in the Select to represent "no override" (null model).
const MODEL_DEFAULT_VALUE = '__default__';

// Sentinel values for the three-state plan mode selector. `global` maps to
// `null` on the wire (follow global setting); `on` / `off` explicitly force
// plan mode for the worker regardless of the global.
const PLAN_MODE_GLOBAL = '__global__';
const PLAN_MODE_ON = 'on';
const PLAN_MODE_OFF = 'off';
type PlanModeChoice =
  | typeof PLAN_MODE_GLOBAL
  | typeof PLAN_MODE_ON
  | typeof PLAN_MODE_OFF;

const planModeToChoice = (value: boolean | null): PlanModeChoice => {
  if (value === true) return PLAN_MODE_ON;
  if (value === false) return PLAN_MODE_OFF;
  return PLAN_MODE_GLOBAL;
};

const choiceToPlanMode = (choice: PlanModeChoice): boolean | null => {
  if (choice === PLAN_MODE_ON) return true;
  if (choice === PLAN_MODE_OFF) return false;
  return null;
};

function LabelWithHelp({
  htmlFor,
  label,
  help,
}: {
  htmlFor: string;
  label: string;
  help: string;
}) {
  return (
    <div className="flex items-center gap-1.5">
      <Label htmlFor={htmlFor}>{label}</Label>
      <Tooltip content={help} side="right">
        <button
          type="button"
          aria-label={help}
          className="inline-flex items-center justify-center rounded text-low hover:text-normal focus:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        >
          <HelpCircle className="h-3.5 w-3.5" aria-hidden />
        </button>
      </Tooltip>
    </div>
  );
}

function SectionHeader({ children }: { children: ReactNode }) {
  return (
    <div className="mt-2 border-b border-border pb-1 text-label font-semibold uppercase tracking-wider text-low">
      {children}
    </div>
  );
}

export interface WorkerFormDialogProps {
  worker?: WorkerResponse;
}

export type WorkerFormResult = 'saved' | 'canceled';

const WorkerFormDialogImpl = create<WorkerFormDialogProps>(({ worker }) => {
  const modal = useModal();
  const { t } = useTranslation('common');
  const isEdit = !!worker;

  const [name, setName] = useState(worker?.name ?? '');
  const [soul, setSoul] = useState(worker?.soul ?? '');
  const [role, setRole] = useState<WorkerRole>(
    (worker?.role as WorkerRole) ?? 'developer'
  );
  const [model, setModel] = useState<string | null>(worker?.model ?? null);
  const [planMode, setPlanMode] = useState<PlanModeChoice>(
    planModeToChoice(readPlanMode(worker))
  );
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // PAT field state.
  //   - `githubPat === null`  → do not touch the stored value (edit mode
  //                             with an existing PAT that the user hasn't
  //                             replaced, OR create mode with no token).
  //   - `githubPat === ''`    → clear the stored value on save.
  //   - `githubPat === <str>` → new value to persist (validated first).
  // We keep the input value separately from what we send to the API so the
  // masked placeholder can render without leaking the real token.
  const [githubPat, setGithubPat] = useState<string | null>(null);
  const [clearPat, setClearPat] = useState(false);
  const [patValidation, setPatValidation] = useState<
    | { status: 'idle' }
    | { status: 'validating' }
    | { status: 'ok'; login: string }
    | { status: 'error'; message: string }
  >({ status: 'idle' });

  const [baseInstructionsExpanded, setBaseInstructionsExpanded] =
    useState(false);
  const { data: baseInstructions } = useBaseInstructions();

  const { config: systemConfig } = useUserSystem();
  const configuredExecutor = systemConfig?.executor_profile?.executor ?? null;
  const { config: modelConfig } = useModelSelectorConfig(configuredExecutor);

  const createMutation = useCreateWorker();
  const updateMutation = useUpdateWorker();
  const isSubmitting = createMutation.isPending || updateMutation.isPending;

  useEffect(() => {
    setName(worker?.name ?? '');
    setSoul(worker?.soul ?? '');
    setRole((worker?.role as WorkerRole) ?? 'developer');
    setModel(worker?.model ?? null);
    setPlanMode(planModeToChoice(readPlanMode(worker)));
    setGithubPat(null);
    setClearPat(false);
    setPatValidation({ status: 'idle' });
    setErrorMessage(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [worker?.id]);

  useEffect(() => {
    setErrorMessage(null);
  }, [name, soul, role, model, planMode, githubPat, clearPat]);

  const applyTemplate = (templateId: SoulTemplateId) => {
    const template = SOUL_TEMPLATES.find((tpl) => tpl.id === templateId);
    if (!template) return;
    setSoul(template.soul);
    if (template.role) setRole(template.role);
  };

  const handleCancel = () => {
    modal.resolve('canceled' as WorkerFormResult);
    modal.hide();
  };

  const handleOpenChange = (open: boolean) => {
    if (!open) handleCancel();
  };

  const handleValidatePat = async () => {
    const trimmed = (githubPat ?? '').trim();
    if (!trimmed) return;
    setPatValidation({ status: 'validating' });
    try {
      const { login } = await workersApi.validateGithubPat(trimmed);
      setPatValidation({ status: 'ok', login });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      setPatValidation({ status: 'error', message });
    }
  };

  const handleSubmit = async () => {
    const trimmedName = name.trim();
    const trimmedSoul = soul.trim();
    if (!trimmedName || !trimmedSoul) return;

    // Decide what to send for github_pat:
    //   - `undefined` → don't touch (server keeps the stored value)
    //   - `null`      → clear the stored token
    //   - `string`    → replace with this value
    // On create there is nothing to clear, so we drop `null` outright and
    // only send a string when the user typed something.
    let github_pat: string | null | undefined;
    const trimmedPat = (githubPat ?? '').trim();
    if (isEdit) {
      if (clearPat) {
        github_pat = null;
      } else if (trimmedPat.length > 0) {
        github_pat = trimmedPat;
      } else {
        github_pat = undefined;
      }
    } else if (trimmedPat.length > 0) {
      github_pat = trimmedPat;
    } else {
      github_pat = undefined;
    }

    const payload: CreateWorkerRequest = {
      name: trimmedName,
      emoji: worker?.emoji ?? DEFAULT_WORKER_EMOJI,
      soul: trimmedSoul,
      role,
      model: model ?? null,
      plan_mode: choiceToPlanMode(planMode),
      ...(github_pat === undefined ? {} : { github_pat }),
    };

    try {
      if (isEdit && worker) {
        await updateMutation.mutateAsync({
          workerId: worker.id,
          data: payload,
        });
      } else {
        await createMutation.mutateAsync(payload);
      }
      modal.resolve('saved' as WorkerFormResult);
      modal.hide();
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      setErrorMessage(message);
    }
  };

  const canSubmit =
    name.trim().length > 0 && soul.trim().length > 0 && !isSubmitting;

  // Warning drives from live textarea contents so the user sees it flip as
  // they edit; falls back to the server's authoritative flag from the loaded
  // response for the initial paint before any keystroke. Non-blocking:
  // saving stays allowed to support gradual migration.
  const soulUnchanged = (worker?.soul ?? '') === soul;
  const showGhWriteWarning = soulUnchanged
    ? readGhWriteWarning(worker) || soulHasGhWritePatterns(soul)
    : soulHasGhWritePatterns(soul);

  const availableModels = modelConfig?.models ?? [];
  const hasModels = availableModels.length > 0;

  const selectValue = model ?? MODEL_DEFAULT_VALUE;

  return (
    <Dialog open={modal.visible} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-[640px]">
        <DialogHeader>
          <DialogTitle>
            {isEdit ? t('workers.form.editTitle') : t('workers.form.newTitle')}
          </DialogTitle>
          <DialogDescription>{t('workers.form.description')}</DialogDescription>
        </DialogHeader>

        <div className="space-y-3 py-2">
          <SectionHeader>{t('workers.form.sectionConfig')}</SectionHeader>

          <div>
            <Label htmlFor="worker-name">{t('workers.form.nameLabel')}</Label>
            <Input
              id="worker-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder={t('workers.form.namePlaceholder')}
              autoFocus
              className="mt-1"
            />
          </div>

          {/* Fluke (the Director) keeps its role: it is the only orchestrator. */}
          {worker?.role !== 'orchestrator' && (
            <div>
              <LabelWithHelp
                htmlFor="worker-role"
                label={t('workers.form.roleLabel')}
                help={t(`workers.roles.${role}Description`)}
              />
              <Select
                value={role}
                onValueChange={(v) => setRole(v as WorkerRole)}
              >
                <SelectTrigger id="worker-role" className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {WORKER_ROLES.map((r) => (
                    <SelectItem key={r} value={r}>
                      {t(`workers.roles.${r}`)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {hasModels && (
            <div>
              <Label htmlFor="worker-model">
                {t('workers.form.modelLabel')}
              </Label>
              <Select
                value={selectValue}
                onValueChange={(v) =>
                  setModel(v === MODEL_DEFAULT_VALUE ? null : v)
                }
              >
                <SelectTrigger id="worker-model" className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={MODEL_DEFAULT_VALUE}>
                    {t('workers.form.modelDefault')}
                  </SelectItem>
                  {availableModels.map((m) => (
                    <SelectItem key={m.id} value={m.id}>
                      {m.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          <div>
            <LabelWithHelp
              htmlFor="worker-plan-mode"
              label={t('workers.form.planModeLabel')}
              help={t('workers.form.planModeHelp')}
            />
            <Select
              value={planMode}
              onValueChange={(v) => setPlanMode(v as PlanModeChoice)}
            >
              <SelectTrigger id="worker-plan-mode" className="mt-1">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={PLAN_MODE_GLOBAL}>
                  {t('workers.form.planModeGlobal')}
                </SelectItem>
                <SelectItem value={PLAN_MODE_ON}>
                  {t('workers.form.planModeOn')}
                </SelectItem>
                <SelectItem value={PLAN_MODE_OFF}>
                  {t('workers.form.planModeOff')}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <SectionHeader>{t('workers.form.sectionIntegration')}</SectionHeader>

          <div>
            <Label htmlFor="worker-github-pat">
              {t('workers.form.githubPatLabel')}
            </Label>
            <div className="mt-1 flex gap-2">
              <Input
                id="worker-github-pat"
                type="password"
                autoComplete="new-password"
                value={githubPat ?? ''}
                onChange={(e) => {
                  setGithubPat(e.target.value);
                  setClearPat(false);
                  setPatValidation({ status: 'idle' });
                }}
                placeholder={
                  isEdit && hasStoredPat(worker) && !clearPat
                    ? t('workers.form.githubPatMaskedPlaceholder')
                    : t('workers.form.githubPatPlaceholder')
                }
                className="flex-1"
              />
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleValidatePat}
                disabled={
                  patValidation.status === 'validating' ||
                  !(githubPat ?? '').trim()
                }
              >
                {patValidation.status === 'validating' && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                {t('workers.form.githubPatValidate')}
              </Button>
            </div>
            {patValidation.status === 'ok' && (
              <p className="mt-1 flex items-center gap-1 text-xs text-green-600">
                <CheckCircle2 className="h-3 w-3" />
                {t('workers.form.githubPatValidateOk', {
                  login: patValidation.login,
                })}
              </p>
            )}
            {patValidation.status === 'error' && (
              <p className="mt-1 text-xs text-destructive">
                {patValidation.message}
              </p>
            )}
            <p className="mt-1 text-xs text-low">
              {t('workers.form.githubPatHelp')}
            </p>
            {isEdit && hasStoredPat(worker) && (
              <div className="mt-1 flex items-center gap-2 text-xs">
                <span className="text-low">
                  {clearPat
                    ? t('workers.form.githubPatWillClear')
                    : t('workers.form.githubPatStored')}
                </span>
                {!clearPat ? (
                  <button
                    type="button"
                    onClick={() => {
                      setClearPat(true);
                      setGithubPat('');
                      setPatValidation({ status: 'idle' });
                    }}
                    className="text-destructive underline"
                  >
                    {t('workers.form.githubPatClear')}
                  </button>
                ) : (
                  <button
                    type="button"
                    onClick={() => setClearPat(false)}
                    className="text-low underline"
                  >
                    {t('workers.form.githubPatUndoClear')}
                  </button>
                )}
              </div>
            )}
          </div>

          <SectionHeader>{t('workers.form.sectionSoul')}</SectionHeader>

          {!isEdit && (
            <div>
              <p className="text-xs text-low mb-1">
                {t('workers.form.templatesLabel')}
              </p>
              <div className="flex flex-wrap gap-2">
                {SOUL_TEMPLATES.map((tpl) => (
                  <Button
                    key={tpl.id}
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => applyTemplate(tpl.id)}
                  >
                    {t(tpl.labelKey)}
                  </Button>
                ))}
              </div>
            </div>
          )}

          <div className="rounded border">
            <button
              type="button"
              onClick={() => setBaseInstructionsExpanded((prev) => !prev)}
              className="flex w-full items-center gap-1.5 px-3 py-2 text-xs text-low hover:text-normal"
            >
              {baseInstructionsExpanded ? (
                <ChevronDown className="h-3 w-3 shrink-0" />
              ) : (
                <ChevronRight className="h-3 w-3 shrink-0" />
              )}
              <span className="font-medium">
                {t('workers.form.systemInstructionsTitle')}
              </span>
              <span className="ml-1 text-low">
                {t('workers.form.systemInstructionsReadOnly')}
              </span>
            </button>
            {baseInstructionsExpanded && (
              <pre className="max-h-48 overflow-auto border-t px-3 py-2 font-mono text-xs text-low whitespace-pre-wrap">
                {baseInstructions ?? '…'}
              </pre>
            )}
          </div>

          <div>
            <Label htmlFor="worker-soul">{t('workers.form.soulLabel')}</Label>
            <Textarea
              id="worker-soul"
              value={soul}
              onChange={(e) => setSoul(e.target.value)}
              rows={6}
              className="mt-1 font-mono text-sm resize-y min-h-[96px]"
              placeholder={t('workers.form.soulPlaceholder')}
            />
          </div>

          {showGhWriteWarning && (
            <Alert variant="warning">
              <AlertTitle>{t('workers.form.ghWriteWarningTitle')}</AlertTitle>
              <AlertDescription>
                {t('workers.form.ghWriteWarningBody')}
              </AlertDescription>
            </Alert>
          )}

          {errorMessage && <Alert variant="destructive">{errorMessage}</Alert>}
        </div>

        <DialogFooter className="border-t border-border/60 pt-4">
          <Button variant="outline" onClick={handleCancel}>
            {t('workers.form.cancel')}
          </Button>
          <Button onClick={handleSubmit} disabled={!canSubmit}>
            {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            {isEdit ? t('workers.form.saveEdit') : t('workers.form.saveNew')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
});

export const WorkerFormDialog = defineModal<
  WorkerFormDialogProps,
  WorkerFormResult
>(WorkerFormDialogImpl);
