import type { WorkerResponse, WorkerTaskResponse } from 'shared/types';

export type Worker = WorkerResponse;

// Extends the generated type with the `skills` field added in #30.
// shared/types.ts will be regenerated by infrastructure once the Rust types
// are compiled; this local extension keeps the frontend compiling in the
// meantime and remains valid after regeneration since the field is additive.
export type WorkerTask = WorkerTaskResponse & { skills?: string[] };

export type SprintColumnStatus =
  | 'backlog'
  | 'queued'
  | 'in_progress'
  | 'in_review'
  | 'done';
