import { useQuery } from '@tanstack/react-query';
import { makeLocalApiRequest } from '@/shared/lib/localApiTransport';
import { useHostId } from '@/shared/providers/HostIdProvider';

/**
 * Local mirrors of the backend types (see
 * `crates/server/src/routes/pilot_report.rs`). Kept in sync manually until
 * the shared types file is regenerated by `pnpm run generate-types`.
 */

export interface PilotReportTask {
  worker_id: string;
  title: string;
  issue_number: number | null;
  status: 'done' | 'failed' | string;
  /** SQLite UTC datetime: "YYYY-MM-DD HH:MM:SS.SSS" */
  completed_at: string;
  /** Per-task hours-saved override; `null` means "use installation default". */
  hours_saved_override: number | null;
  /** Rolled-up LLM cost across every execution under this task, in USD.
   *  `null` when the task never had any usage recorded (older tasks or
   *  agents that don't emit `total_cost_usd` yet). */
  cost_usd: number | null;
  input_tokens: number | null;
  output_tokens: number | null;
  cache_creation_tokens: number | null;
  cache_read_tokens: number | null;
}

export interface PilotReportMergedPr {
  pr_number: number;
  pr_url: string;
  target_branch_name: string;
  /** SQLite UTC datetime: "YYYY-MM-DD HH:MM:SS.SSS" */
  merged_at: string;
}

export interface PilotReportData {
  /** ISO-8601 lower bound (inclusive) actually queried. */
  from: string;
  /** ISO-8601 upper bound (exclusive) actually queried. */
  to: string;
  completed_tasks: PilotReportTask[];
  merged_prs: PilotReportMergedPr[];
}

const EMPTY_DATA: PilotReportData = {
  from: '',
  to: '',
  completed_tasks: [],
  merged_prs: [],
};

/**
 * Fetch the raw signals for the given half-open window `[from, to)`.
 *
 * `from` and `to` are RFC-3339 timestamps; the caller decides the local
 * calendar boundaries. The query is intentionally re-runnable — pushing
 * a new range replaces the previous data without a stale-flash — but is
 * cached per range so switching preset buttons feels instant.
 */
export function usePilotReport(
  from: Date,
  to: Date
): {
  data: PilotReportData;
  isLoading: boolean;
  isFetching: boolean;
  error: unknown;
} {
  const hostId = useHostId();
  const basePath = hostId ? `/api/host/${hostId}` : '/api';

  const fromIso = from.toISOString();
  const toIso = to.toISOString();

  const {
    data = EMPTY_DATA,
    isLoading,
    isFetching,
    error,
  } = useQuery({
    queryKey: ['pilot-report', hostId, fromIso, toIso],
    queryFn: async (): Promise<PilotReportData> => {
      const params = new URLSearchParams({ from: fromIso, to: toIso });
      const response = await makeLocalApiRequest(
        `${basePath}/pilot-report?${params.toString()}`
      );
      if (!response.ok) {
        throw new Error(`pilot report request failed (${response.status})`);
      }
      const payload = await response.json();
      const inner = payload?.data as PilotReportData | undefined;
      return inner ?? EMPTY_DATA;
    },
    // A pilot report is a snapshot; don't churn it in the background.
    refetchOnWindowFocus: false,
    staleTime: 30_000,
  });

  return { data, isLoading, isFetching, error };
}
