import { parse, stringify } from 'yaml';
import {
  isJobNode,
  isTriggerNode,
  JOB_ID_PATTERN,
  needsForNode,
  type PipelineGraph,
  type PipelineJobNode,
  type TriggerSpec,
} from './graph';
import { getPrefab, type WorkflowStep } from './prefabs';

/**
 * Graph → GitHub Actions YAML compiler. Pure and deterministic: the output
 * depends only on the graph's logical content — job order is topological
 * (Kahn) with alphabetical tie-breaks, so canvas positions and node insertion
 * order never show up in diffs.
 */

export interface CompileError {
  /** Node the error is attributed to; null for graph-level errors. */
  nodeId: string | null;
  message: string;
}

export type CompileResult =
  | { ok: true; yaml: string }
  | { ok: false; errors: CompileError[] };

export interface CompileOptions {
  /** Sidecar file name referenced from the generated header. */
  sidecarName?: string;
}

const HEADER = (sidecarName: string): string =>
  `# Generated by Fluke CI Pipeline Studio — do not edit by hand.\n` +
  `# Source of truth: ${sidecarName}\n`;

export function compileGraph(
  graph: PipelineGraph,
  options: CompileOptions = {}
): CompileResult {
  const errors: CompileError[] = [];
  const jobNodes = graph.nodes.filter(isJobNode);
  const triggerNodes = graph.nodes.filter(isTriggerNode);

  // Whole-file passthrough (best-effort import of foreign workflows).
  const fileNodes = jobNodes.filter(
    (n) => n.type === 'raw' && n.scope === 'file'
  );
  if (fileNodes.length > 0) {
    if (graph.nodes.length > 1) {
      errors.push({
        nodeId: fileNodes[0].id,
        message: 'A whole-file YAML node must be the only node in the workflow',
      });
      return { ok: false, errors };
    }
    const fileNode = fileNodes[0];
    if (fileNode.type !== 'raw') {
      // Unreachable; narrows the type.
      throw new Error('expected raw node');
    }
    const yaml = fileNode.yaml;
    return { ok: true, yaml: yaml.endsWith('\n') ? yaml : `${yaml}\n` };
  }

  const seenTriggerKinds = new Set<string>();
  for (const node of triggerNodes) {
    if (seenTriggerKinds.has(node.trigger.kind)) {
      errors.push({
        nodeId: node.id,
        message: `Duplicate trigger: ${node.trigger.kind}`,
      });
    }
    seenTriggerKinds.add(node.trigger.kind);
  }

  if (jobNodes.length === 0) {
    errors.push({ nodeId: null, message: 'The workflow has no jobs' });
  }
  const seenJobIds = new Set<string>();
  for (const node of jobNodes) {
    if (!JOB_ID_PATTERN.test(node.jobId)) {
      errors.push({
        nodeId: node.id,
        message: `Invalid job id "${node.jobId}"`,
      });
    }
    if (seenJobIds.has(node.jobId)) {
      errors.push({
        nodeId: node.id,
        message: `Duplicate job id "${node.jobId}"`,
      });
    }
    seenJobIds.add(node.jobId);
  }

  const ordered = topologicalOrder(graph, jobNodes);
  if (ordered === null) {
    errors.push({
      nodeId: null,
      message: 'The graph has a dependency cycle',
    });
  }

  const jobs: Record<string, unknown> = {};
  if (ordered) {
    for (const node of ordered) {
      const body = compileJob(graph, node, errors);
      if (body !== null) {
        jobs[node.jobId] = body;
      }
    }
  }

  // Workflow-level remainder (env, permissions, concurrency, unsupported
  // `on:` entries …) captured at import time; re-emitted verbatim so the
  // graph never silently drops what it cannot model.
  let extraTopLevel: Record<string, unknown> = {};
  let extraOn: Record<string, unknown> = {};
  if (graph.extras?.workflowYaml) {
    let parsedExtras: unknown;
    try {
      parsedExtras = parse(graph.extras.workflowYaml);
    } catch {
      parsedExtras = undefined;
      errors.push({
        nodeId: null,
        message: 'Invalid YAML in the workflow-level extras',
      });
    }
    if (parsedExtras !== undefined && parsedExtras !== null) {
      if (typeof parsedExtras !== 'object' || Array.isArray(parsedExtras)) {
        errors.push({
          nodeId: null,
          message: 'Workflow-level extras must be a YAML mapping',
        });
      } else {
        const { on: extrasOnValue, ...rest } = parsedExtras as Record<
          string,
          unknown
        >;
        extraTopLevel = rest;
        if (
          extrasOnValue !== undefined &&
          extrasOnValue !== null &&
          typeof extrasOnValue === 'object' &&
          !Array.isArray(extrasOnValue)
        ) {
          extraOn = extrasOnValue as Record<string, unknown>;
        }
      }
    }
  }

  // Triggers can come from nodes or ride along in the extras' `on:` block
  // (kinds the graph does not model yet) — the workflow just needs one.
  if (triggerNodes.length === 0 && Object.keys(extraOn).length === 0) {
    errors.push({
      nodeId: null,
      message: 'The workflow needs at least one trigger',
    });
  }

  if (errors.length > 0) {
    return { ok: false, errors };
  }

  const on = compileTriggers(triggerNodes.map((n) => n.trigger));
  for (const [kind, spec] of Object.entries(extraOn)) {
    // Trigger nodes win for the kinds they model; extras supply the rest.
    if (!(kind in on)) on[kind] = spec;
  }

  const doc: Record<string, unknown> = {
    name: graph.workflowName,
    on,
    ...extraTopLevel,
    jobs,
  };

  const sidecarName = options.sidecarName ?? `${graph.workflowName}.fluke.json`;
  const yaml = stringify(doc, { indent: 2, lineWidth: 0 });
  return { ok: true, yaml: HEADER(sidecarName) + yaml };
}

// ---------------------------------------------------------------------------
// Triggers
// ---------------------------------------------------------------------------

function compileTriggers(triggers: TriggerSpec[]): Record<string, unknown> {
  const on: Record<string, unknown> = {};
  // Fixed emission order regardless of node order on the canvas.
  const byKind = new Map(triggers.map((t) => [t.kind, t]));
  const push = byKind.get('push');
  if (push && push.kind === 'push') {
    const spec: Record<string, unknown> = {};
    if (push.branches.length > 0) spec.branches = push.branches;
    if (push.pathsIgnore && push.pathsIgnore.length > 0) {
      spec['paths-ignore'] = push.pathsIgnore;
    }
    if (push.tags && push.tags.length > 0) spec.tags = push.tags;
    on.push = spec;
  }
  const pullRequest = byKind.get('pull_request');
  if (pullRequest && pullRequest.kind === 'pull_request') {
    const spec: Record<string, unknown> = {};
    if (pullRequest.branches.length > 0) spec.branches = pullRequest.branches;
    on.pull_request = spec;
  }
  const schedule = byKind.get('schedule');
  if (schedule && schedule.kind === 'schedule') {
    on.schedule = [{ cron: schedule.cron }];
  }
  if (byKind.has('workflow_dispatch')) {
    on.workflow_dispatch = {};
  }
  return on;
}

// ---------------------------------------------------------------------------
// Jobs
// ---------------------------------------------------------------------------

function compileJob(
  graph: PipelineGraph,
  node: PipelineJobNode,
  errors: CompileError[]
): Record<string, unknown> | null {
  const needs = needsForNode(graph, node.id);

  if (node.type === 'raw') {
    let parsed: unknown;
    try {
      parsed = parse(node.yaml);
    } catch (error) {
      errors.push({
        nodeId: node.id,
        message: `Invalid YAML in job "${node.jobId}": ${
          error instanceof Error ? error.message : String(error)
        }`,
      });
      return null;
    }
    if (
      parsed === null ||
      typeof parsed !== 'object' ||
      Array.isArray(parsed)
    ) {
      errors.push({
        nodeId: node.id,
        message: `Job "${node.jobId}" YAML must be a mapping`,
      });
      return null;
    }
    const body = { ...(parsed as Record<string, unknown>) };
    // Edges are the single source of truth for `needs`, even inside raw jobs.
    if (needs.length > 0) {
      body.needs = needs;
    } else {
      delete body.needs;
    }
    if (body['runs-on'] === undefined && node.runsOn) {
      body['runs-on'] = node.runsOn;
    }
    return body;
  }

  if (node.type === 'script') {
    if (node.steps.length === 0) {
      errors.push({
        nodeId: node.id,
        message: `Job "${node.jobId}" has no steps`,
      });
      return null;
    }
    for (const step of node.steps) {
      const hasRun = typeof step.run === 'string' && step.run !== '';
      const hasUses = typeof step.uses === 'string' && step.uses !== '';
      if (hasRun === hasUses) {
        errors.push({
          nodeId: node.id,
          message: `Each step of "${node.jobId}" needs either run or uses`,
        });
        return null;
      }
    }
    const body: Record<string, unknown> = {};
    if (node.label && node.label !== node.jobId) {
      body.name = node.label;
    }
    body['runs-on'] = node.runsOn;
    if (needs.length > 0) {
      body.needs = needs;
    }
    if (node.env && Object.keys(node.env).length > 0) {
      body.env = node.env;
    }
    body.steps = node.steps.map(cleanStep);
    return body;
  }

  let steps: WorkflowStep[];
  if (node.type === 'prefab') {
    const prefab = getPrefab(node.prefabId);
    if (!prefab) {
      errors.push({
        nodeId: node.id,
        message: `Unknown prefab "${node.prefabId}"`,
      });
      return null;
    }
    steps = prefab.compile(node.params);
  } else {
    steps = [];
    if (node.checkout) {
      steps.push({ name: 'Checkout', uses: 'actions/checkout@v4' });
    }
    const step: WorkflowStep = { name: node.label, uses: node.uses };
    if (Object.keys(node.with).length > 0) {
      step.with = node.with;
    }
    steps.push(step);
  }

  const body: Record<string, unknown> = {};
  if (node.label && node.label !== node.jobId) {
    body.name = node.label;
  }
  body['runs-on'] = node.runsOn;
  if (needs.length > 0) {
    body.needs = needs;
  }
  body.steps = steps.map(cleanStep);
  return body;
}

/** Emit step keys in a stable, conventional order; empty mappings are
 * dropped rather than emitted as `{}`. */
function cleanStep(step: {
  name?: string;
  uses?: string;
  with?: Record<string, unknown>;
  run?: string;
  env?: Record<string, unknown>;
}): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (step.name !== undefined) out.name = step.name;
  if (step.uses !== undefined) out.uses = step.uses;
  if (step.with !== undefined && Object.keys(step.with).length > 0) {
    out.with = step.with;
  }
  if (step.run !== undefined) out.run = step.run;
  if (step.env !== undefined && Object.keys(step.env).length > 0) {
    out.env = step.env;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Ordering / cycles
// ---------------------------------------------------------------------------

/** Kahn topological sort over job nodes, alphabetical by jobId among ready
 * nodes. Returns null when the graph has a cycle. */
function topologicalOrder(
  graph: PipelineGraph,
  jobNodes: PipelineJobNode[]
): PipelineJobNode[] | null {
  const jobIds = new Set(jobNodes.map((n) => n.id));
  const inDegree = new Map<string, number>(jobNodes.map((n) => [n.id, 0]));
  const outgoing = new Map<string, string[]>();
  for (const edge of graph.edges) {
    if (!jobIds.has(edge.source) || !jobIds.has(edge.target)) continue;
    inDegree.set(edge.target, (inDegree.get(edge.target) ?? 0) + 1);
    const targets = outgoing.get(edge.source) ?? [];
    targets.push(edge.target);
    outgoing.set(edge.source, targets);
  }

  const byId = new Map(jobNodes.map((n) => [n.id, n]));
  const ready = jobNodes
    .filter((n) => (inDegree.get(n.id) ?? 0) === 0)
    .map((n) => n.id);
  const ordered: PipelineJobNode[] = [];

  while (ready.length > 0) {
    ready.sort((a, b) =>
      (byId.get(a)?.jobId ?? '').localeCompare(byId.get(b)?.jobId ?? '')
    );
    const id = ready.shift();
    if (id === undefined) break;
    const node = byId.get(id);
    if (node) ordered.push(node);
    for (const target of outgoing.get(id) ?? []) {
      const degree = (inDegree.get(target) ?? 0) - 1;
      inDegree.set(target, degree);
      if (degree === 0) ready.push(target);
    }
  }

  return ordered.length === jobNodes.length ? ordered : null;
}

/** Dry-run cycle check used by the store to reject a connection before it is
 * added: connecting source→target creates a cycle iff source is reachable
 * from target. */
export function wouldCreateCycle(
  graph: PipelineGraph,
  source: string,
  target: string
): boolean {
  if (source === target) return true;
  const outgoing = new Map<string, string[]>();
  for (const edge of graph.edges) {
    const targets = outgoing.get(edge.source) ?? [];
    targets.push(edge.target);
    outgoing.set(edge.source, targets);
  }
  const stack = [target];
  const visited = new Set<string>();
  while (stack.length > 0) {
    const current = stack.pop();
    if (current === undefined) break;
    if (current === source) return true;
    if (visited.has(current)) continue;
    visited.add(current);
    for (const next of outgoing.get(current) ?? []) {
      stack.push(next);
    }
  }
  return false;
}
