import { describe, expect, it } from 'vitest';
import { compileGraph, wouldCreateCycle } from './compiler';
import {
  PIPELINE_GRAPH_VERSION,
  type PipelineEdge,
  type PipelineGraph,
  type PipelineNode,
} from './graph';

function graphOf(
  nodes: PipelineNode[],
  edges: PipelineEdge[] = [],
  workflowName = 'ci'
): PipelineGraph {
  return { version: PIPELINE_GRAPH_VERSION, workflowName, nodes, edges };
}

function pushTrigger(id = 't1'): PipelineNode {
  return {
    type: 'trigger',
    id,
    position: { x: 0, y: 0 },
    trigger: { kind: 'push', branches: ['main'] },
  };
}

function marketplaceJob(
  id: string,
  jobId: string,
  position = { x: 0, y: 0 }
): PipelineNode {
  return {
    type: 'marketplace',
    id,
    jobId,
    label: jobId,
    runsOn: 'ubuntu-latest',
    position,
    uses: 'actions/checkout@v4',
    with: {},
    checkout: false,
  };
}

function edge(source: string, target: string): PipelineEdge {
  return { id: `e-${source}-${target}`, source, target };
}

function expectOk(graph: PipelineGraph): string {
  const result = compileGraph(graph, { sidecarName: 'ci.fluke.json' });
  if (!result.ok) {
    throw new Error(
      `expected ok, got errors: ${result.errors.map((e) => e.message).join('; ')}`
    );
  }
  return result.yaml;
}

describe('compileGraph', () => {
  it('compiles a minimal push + prefab workflow', () => {
    const graph = graphOf([
      pushTrigger(),
      {
        type: 'prefab',
        id: 'j1',
        jobId: 'build',
        label: 'Node.js build',
        runsOn: 'ubuntu-latest',
        position: { x: 0, y: 0 },
        prefabId: 'node-build',
        params: {
          nodeVersion: '20',
          packageManager: 'pnpm',
          buildCommand: 'pnpm build',
        },
      },
    ]);
    const yaml = expectOk(graph);
    expect(yaml).toContain(
      '# Generated by Fluke CI Pipeline Studio — do not edit by hand.'
    );
    expect(yaml).toContain('# Source of truth: ci.fluke.json');
    expect(yaml).toContain('name: ci');
    expect(yaml).toContain('push:');
    expect(yaml).toContain('- main');
    expect(yaml).toContain('build:');
    expect(yaml).toContain('uses: actions/checkout@v4');
    expect(yaml).toContain('uses: pnpm/action-setup@v4');
    expect(yaml).toContain('node-version: "20"');
    expect(yaml).toContain('run: pnpm install --frozen-lockfile');
  });

  it('derives needs from edges in a diamond graph', () => {
    const graph = graphOf(
      [
        pushTrigger(),
        marketplaceJob('a', 'build'),
        marketplaceJob('b', 'lint'),
        marketplaceJob('c', 'test'),
        marketplaceJob('d', 'deploy'),
      ],
      [edge('a', 'b'), edge('a', 'c'), edge('b', 'd'), edge('c', 'd')]
    );
    const yaml = expectOk(graph);
    // deploy needs both branches of the diamond, sorted.
    expect(yaml).toMatch(/deploy:[\s\S]*?needs:\n\s+- lint\n\s+- test/);
    // build has no needs.
    expect(yaml).not.toMatch(/build:[\s\S]{0,80}needs:/);
  });

  it('output is independent of node order and canvas positions', () => {
    const nodes = [
      pushTrigger(),
      marketplaceJob('a', 'build', { x: 10, y: 20 }),
      marketplaceJob('b', 'test', { x: 300, y: 40 }),
    ];
    const edges = [edge('a', 'b')];
    const baseline = expectOk(graphOf(nodes, edges));

    const reordered = graphOf(
      [
        marketplaceJob('b', 'test', { x: 999, y: 999 }),
        pushTrigger(),
        marketplaceJob('a', 'build', { x: -50, y: 0 }),
      ],
      edges
    );
    expect(expectOk(reordered)).toBe(baseline);
  });

  it('orders independent jobs alphabetically', () => {
    const graph = graphOf([
      pushTrigger(),
      marketplaceJob('z', 'zeta'),
      marketplaceJob('a', 'alpha'),
    ]);
    const yaml = expectOk(graph);
    expect(yaml.indexOf('alpha:')).toBeLessThan(yaml.indexOf('zeta:'));
  });

  it('edges override needs inside raw job YAML', () => {
    const graph = graphOf(
      [
        pushTrigger(),
        marketplaceJob('a', 'build'),
        {
          type: 'raw',
          id: 'r1',
          jobId: 'custom',
          label: 'custom',
          runsOn: 'ubuntu-latest',
          position: { x: 0, y: 0 },
          scope: 'job',
          yaml: 'runs-on: macos-14\nneeds: [stale-job]\nsteps:\n  - run: echo hi\n',
        },
      ],
      [edge('a', 'r1')]
    );
    const yaml = expectOk(graph);
    expect(yaml).not.toContain('stale-job');
    expect(yaml).toMatch(/custom:[\s\S]*?needs:\n\s+- build/);
    // Raw body's own runs-on is preserved.
    expect(yaml).toContain('runs-on: macos-14');
  });

  it('passes a whole-file raw node through byte-identical (plus newline)', () => {
    const foreign =
      '# hand-written\non: [push]\njobs:\n  x:\n    runs-on: ubuntu-latest\n    steps:\n      - run: make';
    const graph = graphOf([
      {
        type: 'raw',
        id: 'f1',
        jobId: 'imported',
        label: 'ci',
        runsOn: '',
        position: { x: 0, y: 0 },
        scope: 'file',
        yaml: foreign,
      },
    ]);
    expect(expectOk(graph)).toBe(`${foreign}\n`);
  });

  it('rejects cycles', () => {
    const graph = graphOf(
      [pushTrigger(), marketplaceJob('a', 'one'), marketplaceJob('b', 'two')],
      [edge('a', 'b'), edge('b', 'a')]
    );
    const result = compileGraph(graph);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.errors.some((e) => e.message.includes('cycle'))).toBe(true);
    }
  });

  it('rejects duplicate job ids and missing triggers', () => {
    const result = compileGraph(
      graphOf([marketplaceJob('a', 'dup'), marketplaceJob('b', 'dup')])
    );
    expect(result.ok).toBe(false);
    if (!result.ok) {
      const messages = result.errors.map((e) => e.message).join('\n');
      expect(messages).toContain('Duplicate job id');
      expect(messages).toContain('at least one trigger');
    }
  });

  it('compiles every trigger kind', () => {
    const graph = graphOf([
      pushTrigger('t1'),
      {
        type: 'trigger',
        id: 't2',
        position: { x: 0, y: 0 },
        trigger: { kind: 'pull_request', branches: ['main'] },
      },
      {
        type: 'trigger',
        id: 't3',
        position: { x: 0, y: 0 },
        trigger: { kind: 'schedule', cron: '0 6 * * 1' },
      },
      {
        type: 'trigger',
        id: 't4',
        position: { x: 0, y: 0 },
        trigger: { kind: 'workflow_dispatch' },
      },
      marketplaceJob('a', 'build'),
    ]);
    const yaml = expectOk(graph);
    expect(yaml).toContain('push:');
    expect(yaml).toContain('pull_request:');
    expect(yaml).toContain('cron: 0 6 * * 1');
    expect(yaml).toContain('workflow_dispatch: {}');
  });
});

describe('wouldCreateCycle', () => {
  const graph = graphOf(
    [
      marketplaceJob('a', 'one'),
      marketplaceJob('b', 'two'),
      marketplaceJob('c', 'three'),
    ],
    [edge('a', 'b'), edge('b', 'c')]
  );

  it('detects back-edges and self-edges', () => {
    expect(wouldCreateCycle(graph, 'c', 'a')).toBe(true);
    expect(wouldCreateCycle(graph, 'a', 'a')).toBe(true);
  });

  it('allows forward and lateral edges', () => {
    expect(wouldCreateCycle(graph, 'a', 'c')).toBe(false);
  });
});
