/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSignInRouteImport } from './routes/onboarding_.sign-in'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppWorkersRouteImport } from './routes/_app.workers'
import { Route as AppSprintRouteImport } from './routes/_app.sprint'
import { Route as AppSourceControlRouteImport } from './routes/_app.source-control'
import { Route as AppPilotReportRouteImport } from './routes/_app.pilot-report'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppIssuesRouteImport } from './routes/_app.issues'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCiPipelinesRouteImport } from './routes/_app.ci-pipelines'
import { Route as WorkspacesWorkspaceIdVscodeRouteImport } from './routes/workspaces.$workspaceId.vscode'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app.workspaces_.$workspaceId'
import { Route as AppIssuesIssueNumberRouteImport } from './routes/_app.issues_.$issueNumber'
import { Route as AppHostsHostIdWorkspacesRouteImport } from './routes/_app.hosts.$hostId.workspaces'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'
import { Route as AppHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.hosts.$hostId.workspaces_.$workspaceId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignInRoute = OnboardingSignInRouteImport.update({
  id: '/onboarding_/sign-in',
  path: '/onboarding/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersRoute = AppWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AppRoute,
} as any)
const AppSprintRoute = AppSprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => AppRoute,
} as any)
const AppSourceControlRoute = AppSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => AppRoute,
} as any)
const AppPilotReportRoute = AppPilotReportRouteImport.update({
  id: '/pilot-report',
  path: '/pilot-report',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCiPipelinesRoute = AppCiPipelinesRouteImport.update({
  id: '/ci-pipelines',
  path: '/ci-pipelines',
  getParentRoute: () => AppRoute,
} as any)
const WorkspacesWorkspaceIdVscodeRoute =
  WorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/workspaces/$workspaceId/vscode',
    path: '/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppIssuesIssueNumberRoute = AppIssuesIssueNumberRouteImport.update({
  id: '/issues_/$issueNumber',
  path: '/issues/$issueNumber',
  getParentRoute: () => AppRoute,
} as any)
const AppHostsHostIdWorkspacesRoute =
  AppHostsHostIdWorkspacesRouteImport.update({
    id: '/hosts/$hostId/workspaces',
    path: '/hosts/$hostId/workspaces',
    getParentRoute: () => AppRoute,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    path: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppHostsHostIdWorkspacesWorkspaceIdRoute =
  AppHostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/ci-pipelines': typeof AppCiPipelinesRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/issues': typeof AppIssuesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pilot-report': typeof AppPilotReportRoute
  '/source-control': typeof AppSourceControlRoute
  '/sprint': typeof AppSprintRoute
  '/workers': typeof AppWorkersRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/issues/$issueNumber': typeof AppIssuesIssueNumberRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/ci-pipelines': typeof AppCiPipelinesRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/issues': typeof AppIssuesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pilot-report': typeof AppPilotReportRoute
  '/source-control': typeof AppSourceControlRoute
  '/sprint': typeof AppSprintRoute
  '/workers': typeof AppWorkersRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/issues/$issueNumber': typeof AppIssuesIssueNumberRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/ci-pipelines': typeof AppCiPipelinesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/export': typeof AppExportRoute
  '/_app/issues': typeof AppIssuesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pilot-report': typeof AppPilotReportRoute
  '/_app/source-control': typeof AppSourceControlRoute
  '/_app/sprint': typeof AppSprintRoute
  '/_app/workers': typeof AppWorkersRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/onboarding_/sign-in': typeof OnboardingSignInRoute
  '/_app/issues_/$issueNumber': typeof AppIssuesIssueNumberRoute
  '/_app/workspaces_/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/_app/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/_app/hosts/$hostId/workspaces_/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/ci-pipelines'
    | '/dashboard'
    | '/export'
    | '/issues'
    | '/notifications'
    | '/pilot-report'
    | '/source-control'
    | '/sprint'
    | '/workers'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/issues/$issueNumber'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/workspaces'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/ci-pipelines'
    | '/dashboard'
    | '/export'
    | '/issues'
    | '/notifications'
    | '/pilot-report'
    | '/source-control'
    | '/sprint'
    | '/workers'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/issues/$issueNumber'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/workspaces'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/ci-pipelines'
    | '/_app/dashboard'
    | '/_app/export'
    | '/_app/issues'
    | '/_app/notifications'
    | '/_app/pilot-report'
    | '/_app/source-control'
    | '/_app/sprint'
    | '/_app/workers'
    | '/_app/workspaces'
    | '/onboarding_/sign-in'
    | '/_app/issues_/$issueNumber'
    | '/_app/workspaces_/$workspaceId'
    | '/workspaces/$workspaceId/vscode'
    | '/_app/hosts/$hostId/workspaces'
    | '/_app/hosts/$hostId/workspaces_/$workspaceId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OnboardingSignInRoute: typeof OnboardingSignInRoute
  WorkspacesWorkspaceIdVscodeRoute: typeof WorkspacesWorkspaceIdVscodeRoute
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/sign-in': {
      id: '/onboarding_/sign-in'
      path: '/onboarding/sign-in'
      fullPath: '/onboarding/sign-in'
      preLoaderRoute: typeof OnboardingSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workers': {
      id: '/_app/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AppWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sprint': {
      id: '/_app/sprint'
      path: '/sprint'
      fullPath: '/sprint'
      preLoaderRoute: typeof AppSprintRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/source-control': {
      id: '/_app/source-control'
      path: '/source-control'
      fullPath: '/source-control'
      preLoaderRoute: typeof AppSourceControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pilot-report': {
      id: '/_app/pilot-report'
      path: '/pilot-report'
      fullPath: '/pilot-report'
      preLoaderRoute: typeof AppPilotReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues': {
      id: '/_app/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ci-pipelines': {
      id: '/_app/ci-pipelines'
      path: '/ci-pipelines'
      fullPath: '/ci-pipelines'
      preLoaderRoute: typeof AppCiPipelinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/workspaces/$workspaceId/vscode': {
      id: '/workspaces/$workspaceId/vscode'
      path: '/workspaces/$workspaceId/vscode'
      fullPath: '/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof WorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces_/$workspaceId': {
      id: '/_app/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues_/$issueNumber': {
      id: '/_app/issues_/$issueNumber'
      path: '/issues/$issueNumber'
      fullPath: '/issues/$issueNumber'
      preLoaderRoute: typeof AppIssuesIssueNumberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces': {
      id: '/_app/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/_app/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCiPipelinesRoute: typeof AppCiPipelinesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportRoute: typeof AppExportRoute
  AppIssuesRoute: typeof AppIssuesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPilotReportRoute: typeof AppPilotReportRoute
  AppSourceControlRoute: typeof AppSourceControlRoute
  AppSprintRoute: typeof AppSprintRoute
  AppWorkersRoute: typeof AppWorkersRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppIssuesIssueNumberRoute: typeof AppIssuesIssueNumberRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
  AppHostsHostIdWorkspacesRoute: typeof AppHostsHostIdWorkspacesRoute
  AppHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCiPipelinesRoute: AppCiPipelinesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportRoute: AppExportRoute,
  AppIssuesRoute: AppIssuesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPilotReportRoute: AppPilotReportRoute,
  AppSourceControlRoute: AppSourceControlRoute,
  AppSprintRoute: AppSprintRoute,
  AppWorkersRoute: AppWorkersRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppIssuesIssueNumberRoute: AppIssuesIssueNumberRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
  AppHostsHostIdWorkspacesRoute: AppHostsHostIdWorkspacesRoute,
  AppHostsHostIdWorkspacesWorkspaceIdRoute:
    AppHostsHostIdWorkspacesWorkspaceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OnboardingSignInRoute: OnboardingSignInRoute,
  WorkspacesWorkspaceIdVscodeRoute: WorkspacesWorkspaceIdVscodeRoute,
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
